from setuptools import setup, find_packages

setup(
    name='crecerelle',
    version='0.1.0',
    author='Friedrich-Maximilian Weberling',
    packages=find_packages(where='src'),
    package_dir={'': 'src'},
    package_data={'crecerelle.default_figures': ['*.png'],},
    include_package_data=True,
    license='MIT',
    classifiers=[
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'License :: OSI Approved :: MIT License',
    ],
    install_requires=[
        'torch>=1.10.0',
        'anndata',
        'scanpy',
        'numpyro',
        'pandas',
        'numpy',
        'matplotlib',
        'seaborn',
        'scikit-learn',
        'umap-learn',
        'leidenalg',
        'igraph',
        'scib',
        'upsetplot',
        'gprofiler-official',
        'matplotlib-venn',
    ],
    python_requires='>=3.10',
    description='Crecerelle: Unimodal and bimodal cell embeddings of single cell gene expression and transcript usage data using (bimodal) variational autoencoders',
)