TABULA_MURIS_CELL_ONTOLOGY = [
    'B cell', 'Bergmann glial cell',
    'Brush cell of epithelium proper of large intestine',
    'CD4-positive, alpha-beta T cell',
    'CD8-positive, alpha-beta T cell', 'DN4 thymocyte', 'Kupffer cell',
    'NK cell', 'T cell', 'adventitial cell', 'aortic endothelial cell',
    'astrocyte', 'atrial myocyte', 'basal cell',
    'basal cell of epidermis',
    'basal epithelial cell of tracheobronchial tree', 'basophil',
    'bladder cell', 'bladder urothelial cell', 'brain pericyte',
    'bronchial smooth muscle cell', 'bulge keratinocyte',
    'chondrocyte', 'ciliated columnar cell of tracheobronchial tree',
    'classical monocyte', 'club cell of bronchiole', 'dendritic cell',
    'early pro-B cell', 'endocardial cell', 'endothelial cell',
    'endothelial cell of coronary artery',
    'endothelial cell of hepatic sinusoid',
    'endothelial cell of lymphatic vessel',
    'enterocyte of epithelium of large intestine',
    'enteroendocrine cell', 'ependymal cell', 'epidermal cell',
    'epithelial cell', 'epithelial cell of large intestine',
    'epithelial cell of proximal tubule', 'epithelial cell of thymus',
    'fenestrated cell', 'fibroblast', 'fibroblast of cardiac tissue',
    'fibroblast of lung', 'fibrocyte', 'granulocyte',
    'granulocyte monocyte progenitor cell', 'granulocytopoietic cell',
    'hematopoietic stem cell', 'hepatocyte', 'immature B cell',
    'intermediate monocyte', 'interneuron',
    'intestinal crypt stem cell', 'keratinocyte',
    'keratinocyte stem cell', 'kidney collecting duct epithelial cell',
    'kidney collecting duct principal cell',
    'kidney loop of Henle ascending limb epithelial cell',
    'large intestine goblet cell', 'late pro-B cell', 'leukocyte',
    'luminal epithelial cell of mammary gland', 'lung macrophage',
    'lung neuroendocrine cell', 'lymphocyte', 'macrophage',
    'mature NK T cell', 'mature alpha-beta T cell',
    'medium spiny neuron', 'megakaryocyte-erythroid progenitor cell',
    'mesangial cell', 'mesenchymal stem cell',
    'mesenchymal stem cell of adipose', 'microglial cell', 'monocyte',
    'mucus secreting cell', 'myeloid cell', 'myeloid dendritic cell',
    'myeloid leukocyte', 'naive B cell', 'neuroepithelial cell',
    'neuron', 'neuronal stem cell', 'neutrophil',
    'non-classical monocyte', 'oligodendrocyte',
    'oligodendrocyte precursor cell', 'pancreatic A cell',
    'pancreatic B cell', 'pancreatic D cell', 'pancreatic PP cell',
    'pancreatic acinar cell', 'pancreatic ductal cell',
    'pancreatic stellate cell', 'pericyte cell',
    'plasmacytoid dendritic cell', 'precursor B cell',
    'proerythroblast', 'professional antigen presenting cell',
    'promonocyte', 'pulmonary interstitial fibroblast',
    'regulatory T cell', 'respiratory basal cell', 'secretory cell',
    'skeletal muscle satellite cell', 'smooth muscle cell',
    'smooth muscle cell of the pulmonary artery',
    'smooth muscle cell of trachea', 'stromal cell', 'thymocyte',
    'type I pneumocyte', 'type II pneumocyte', 'valve cell',
    'vein endothelial cell', 'ventricular myocyte'
]
